Feature/transactions-and-agregated-functions
Hope1226/db-vet-clinic pull request #2
Opened 2022-01-11 23:39 UTC by Hope1226

In this feature branch I:
- Added another list of animals to the table - animals;
- Added a new column called species;
- Added transaction activities;
- Added aggregate functions for analytical queries;

2022-01-12 00:28 UTC, DanSam5K requested changes
## Hi @Hope1226,  ♻️ Required Changes ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![ ](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 00:28 UTC, DanSam5K commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01'  AND '2000-12-31' GROUP BY species;
- [ ] Please update the animal's table by setting the species column to digimon for all animals that have a name ending in 'mon' as instructed and any other update query.
- [ ] Also as instructed I think you have a query that `DELETE` all animals born after Jan 1st, 2022

2022-01-12 00:35 UTC, Hope1226 commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01'  AND '2000-12-31' GROUP BY species;
HI @DanSam5K , thanks for your review and feedback! please note that all that operations are done and saved in data.sql file since they manipulate the data in the table and do not query (that was my logic at least).

2022-01-12 14:34 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🎉🍾✔**
Hello @Hope1226 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 15:02 UTC, merged

2022-01-18 16:39 UTC, DanSam5K commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01'  AND '2000-12-31' GROUP BY species;
Noted